### ISSUE TITLE
kinetic duelist/kinetic lancer stuck during combat

### ISSUE THREAD

**Issue by astrocastro** [NosVladimir/KineticArchetypes#12]
i'm not sure what triggers it but the kinetic lancer and kinetic duelist at times get stuck during combat with the drawing weapon effect going continuously in real time or they stay frozen in spot during turn-based.

**Comment by NosVladimir** [comment]
That's most likely due to there is actually not sufficient burn for the kinetic blade (not due to taking burn from the blade attack itself), is that the case for you? Characters will try to deactivate the blade in this situation, but the game shouldn't allowe them to turn on the blade again.

**Comment by astrocastro** [comment]
Actually, I think that I've identified the issue; their seems to be some conflict with inspired rage with lesser beast totem.

**Comment by NosVladimir** [comment]
Oh, rage... It can also be because of rage - FYI, if you are using any mods (e.g. DarkCodex) to turn kinetic blasts into spell-like abilities, then spells and spell-like abilities including the blasts will be disallowed during rage, unless you have the Mad Magic feat from DarkCodex which allows you to cast spells during rage

**Comment by astrocastro** [comment]
ah, that worked, thank you for the quick response!
