### ISSUE TITLE
The Onslaught Blaster has bug: convert damage into number of blasts only trigger once!

### ISSUE THREAD

**Issue by lufuel** [NosVladimir/KineticArchetypes#19]
I tested the Onslaught Blaster, the character get Kinetic Blast 2 (2d6) at level 3.The first time he cast any Kinetic Blast, it seems right the number of blasts is 2. But after that the second time he cast a Kinetic Blast, the number fall to 1, and the character permanently lost the abilty Kinetic Blast 2 (2d6). Anyway change the KB dmg will trigger this bug like level up and equipment.Burn,metakinesis is working right.

**Comment by NosVladimir** [comment]
Thanks for reporting. I'll have a look as soon as possible

**Comment by lufuel** [comment]
Not testing the rod , wear a headgear increase the dice can trigger the bug as well.

**Comment by NosVladimir** [comment]
I've justed and it's fine on my side. At 20th level and having kinetic diadem equipped, repeatedly cast fire blast or fan of flames always gives 12 times. Taking the diadem on and off, and the numbers change between 12 to 10 correctly. Could you try to respec and see if the problem is still there?

A note on how onslaught blast is implemented: I need to record the level of kinetic blast feature, that's the one to determine the number of damage dices of blasts. An onslaught blast temporarily reduces the level to 1, then casts as many times as the original level, and at the end of cast reverts the level back. For that reason all equipment slots are locked during the cast, to prevent the cases of equipping/unequipping diadems during cast unintentionally changing the dice to 2/0. 

Then there is indeed a bug - during the cast if you level up and receive a dice, that would not be recorded and you will lose that dice after the cast when the level is reverted. But this bug should not be related to the issue you're having

**Comment by lufuel** [comment]
I tested again and kept all mod inactived except this, the bug still trigger. Creating a new 20th level onslaught blaster in first sence of dlc1, outside the battle with no enemy, then cast the fan of flame. Only the first cast has 10 times. When I paused during the cast, I found all equipment slots were locked  and the blast level reduced to 1 as description. But at the end of cast the level of blast didn't reverts back.

**Comment by lufuel** [comment]
Tested again, never revert back after long time past. Is there anyway to get a debug log or check the parameters? I suspect I downloaded the wrong mod file or a wrong version of UMM?

**Comment by NosVladimir** [comment]
Hmm that's strange. You can try to re-download the newest release. I'll take another look soon

**Comment by NosVladimir** [comment]
I managed to reproduce this issue, but only in DLC1!! It's very strange that this bug does not happen for main game, at least for my save. The problem was that the recorder for the blast rank stayed in 1 and didn't update to 10, so despite it's properly reverting, the number was wrong. Also the other behaviour of repeating the first blast after un-equipping the equipment was due to the recorder not being updated. I guess there's something to do with how DLC1 creates the new character, or with how the DLC game version has changed when internal things get updated, but I'm not sure.

The fix is rather simple. I've added another trigger for updating the recorder, so it's fine now. I've updated a new version and tested with a DLC1 new character. It should be working now! Apologise for this annoying bug. 

I also fixed the blue flame wall being able to get onslaught-ed, that's a good catch of a special case I didn't think of.
