### ISSUE TITLE
Kinetic spear seems to give reach to things it shouldn't

### ISSUE THREAD

**Issue by Vilacard** [NosVladimir/KineticArchetypes#25]
From my very little time playing with kinetic lancer (love FF dragoons, so this archetype seems awesome. Thanks for implementing it!) kinetic spear seems to grant reach to secondary attacks that it shouldn't. Particularly I have a kitsune character which has a secondary bite attack, and that bite attack also seems to have reach when I have kinetic spear enabled.

Edit-
A few more things I noticed while playing lancer I'm not so sure about. If you would prefer me to open a different ticket for these I can.

If I dragoon dive and miss, I keep the reduced cost to kinetic blade until I do hit, across turns. At least from what I read from the ability, only the kinetic blade attack as part of the dive should have a reduced cost.

I don't think I'm getting the 0 cost kinetic blade I should at level 1. I'm level 5 right now and it still costs 1.

I don't think infusions in general, or at the very least bowling infusion and kinetic spear, are increasing burn cost as they should. Assuming I have this right, kinetic blade with spear and bowling infusion should cost 4 I think at level 5. Or maybe 3 if you go by how it's written in PnP I think?

**Comment by Vilacard** [comment]
A few more things I noticed while playing lancer I'm not so sure about. If you would prefer me to open a different ticket for these I can.

If I dragoon dive and miss, I keep the reduced cost to kinetic blade until I do hit, across turns. At least from what I read from the ability, only the kinetic blade attack as part of the dive should have a reduced cost.

I don't think I'm getting the 0 cost kinetic blade I should at level 1. I'm level 5 right now and it still costs 1.

I don't think infusions in general, or at the very least bowling infusion and kinetic spear, are increasing burn cost as they should. Assuming I have this right, kinetic blade with spear and bowling infusion should cost 4 I think at level 5. Or maybe 3 if you go by how it's written in PnP I think?

**Comment by Vilacard** [comment]
Woops. Didn't mean to mark as completed.

**Comment by NosVladimir** [comment]
Thanks for reporting.

Actually, when I implemented kinetic lancer, I didn't know it was a FF reference coz I never played FF...

From what I remember, the reach issue may not be easily solvable because I can't create new weapon blueprints to replace what's equipped when you click the button to activate kinetic blades. So I ended up just giving the character a reach buff, and this unfortunately (or, fortunately?) affects bites and headbutts, etc.

The reduced cost continued across turns on a missed dragoon dive is definitely a bug.

Infusions not affecting kinetic blades (and blade derivatives like kinetic spear) may be related to a base game bug where infusions just don't affect kinetic blades. Owlcat simply didn't include kinetic blades in the part of code where the each infusion specifies a list of what blasts they apply the cost increase to. But I do remember I specifically wrote some code to enforce my mod infusions to apply to blades (including kinetic spear and a bunch of other stuff). I'll re-do some calculations and see if the numbers match.

I'll take a look into these issues by the weekend.

**Comment by Vilacard** [comment]
The infusions (or at least Bowling Infusion) do affect blade/spear. I get trip attempts when I land a hit. 

The issue is the burn increases from infusions doesn't seem to work properly. I was mistaken before in thinking Blade didn't get its own decrease and spear didn't increase it all. That part seems to work fine: At level 5 Kinetic Blade alone costs 0 burn. Turn on Kinetic Spear and the burn increases to 1. Bowling infusion (haven't tried any others yet) doesn't seem to increase the burn cost at all. With all 3 together I should have a burn cost of 3 I think (1 from blade, 2 from spear, -1 to each from the dragon dive feat at level 1, then 2 from bowling infusion)., but instead its still a burn cost of 1.

**Comment by NosVladimir** [comment]
Sorry, my bad, in the last paragraph of my previous comment, it should be "substance infusion costs..." rather than "infusions..." alone. 

Yeah, in the unmodded base game, the cost of substance infusions are never added into kinetic blades, but their special effects are. Another example is burning infusion on fire blade, and another more extreme example is pure-flame infusion on blue-flame blade (you ignore spell resistance with no cost increase at all). I know this is absolutely mad and overpowered, but to fix this base game bug is too tedious since one needs to manually go through and fix all substance infusions according to which kinetic blades they should apply to.

So, on this one, consider it a nice little legal cheat...

**Comment by Vilacard** [comment]
Huh, well then. Could've sworn they did add to the burn cost for kinetic blade but I may have been thinking of Kingmaker instead.

Thanks for the info!

**Comment by NosVladimir** [comment]
It's been a few years since I last played kingmaker. If you had Call of the Wilds installed, maybe it had fixed this burn cost bug?

The dragoon dive burn cost reduction remaining on a missed hit bug should be fixed in the [newest release v1.1.6](https://github.com/NosVladimir/KineticArchetypes/releases/tag/v1.1.6).

The reach issue I can't fix, and I've added it to the list of known issues in the readme. The infusion burn cost is a base game bug. Shall we close the issue now?

**Comment by Vilacard** [comment]
When I did play Kingmaker (last time was before Wrath came out) I did have Call of the Wild so it may very well have fixed it in kingmaker.

After a quick test Dragoon Dive burn reduction sticking around after a miss does seem to be fixed.

Thanks for the work!

**Comment by Vilacard** [comment]
Actually found another issue with the burn reduction from dragoon dive sticking around. If i use dragoon dive but fail the mobility/jump check, the burn reduction for blade sticks around until I land a hit.

**Comment by NosVladimir** [comment]
The first is intended - the burn reduction buff only removes itself when you do an attack, regardless of whether it's a hit or not (after today's update). This is to factor in cases where the jump itself lasts longer than 6 seconds, which should be achievable in higher levels when you do an extremely long jump across the map. Then you'd also get a properly reduced-cost attack. If instead the buff disappers in 6 seconds, it could mean that you waste some burns or that you don't have sufficient burn to attack because the burn reduction wears off when you land.

The second had always been a mystery - it's sometimes reported by others too, but all of us can only replicate this issue in when dragoon dive is used to engage into a fight. The enemy you are targeting may be moving, but the landing point is decided when you perform the jump since unfortunately I don't really know how to dynamically update the leaping path. If not triggered as the engaging move, this bug/issue seems to appear rarely and randomly, and I don't have an idea why...

**Comment by Vilacard** [comment]
Found another issue: If I click on an enemy after successfully dragoon diving and landing the attack, I'll take the burn I would've taken without diving. It'll happen even if clicking does nothing: no actions left, used my 5ft step, etc.

**Comment by NosVladimir** [comment]
Is that under turn based or real time with pause?

**Comment by Vilacard** [comment]
Turn based.

**Comment by Vilacard** [comment]
Also, now that I'm playing some more I'm noticed the no attack after dragoon dive happening a lot more often. Even during turn based where the target isn't moving.

**Comment by NosVladimir** [comment]
I've made a new release. I changed the code which issues an attack at the end of jump within dragoon dive. Let me know if the random failure of this attack still appears.

Regarding accepting burn on a click, after some more testing it seems also a base game bug. In the case where you haven't accepted burn from kinetic blades in a turn, and you click on an enemy, even if your actions are all depeleted, the game still thinks you would like to do an attack, so it makes you accept burn if you haven't in the same turn accepted burn from kinetic blades. Then since all actions are depleted, the attack couldn't go ahead. This can also be triggered by, e.g., first do a regular kinetic blast, then equipping kinetic blade, then clicking on an enemy - the game makes you accept the burn for the blade. However, if you accept burn like this in turn 1, then in the next turn (turn 2) you don't need to accept the same burn for making a blade attack. However, if you then click on the enemy again after attacking in turn 2, the same story happens - since turn 2 burn had been accepted in turn 1, you _haven't accepted burn from kinetic blades in turn 2_, so you'd pay some new burn, which is like pre-purchasing a blade attack in a future turn 3. In the end, the order in which the burn gets accepted and the attack is made is just completely messed up, lol.

Going back to the dragoon dive case, because of the burn reduction mechanism of dragoon dive, this falls under _you haven't accepted burn from kinetic blades in this turn_, so clicking on an enemy triggers the said bug. I have no idea how to fix this, and this may even have weirder interactions if at later levels you enable a few things to make dragoon dive actually cost some burn. My suggestion therefore is: don't click on the enemy after dragoon-diving.

**Comment by Vilacard** [comment]
It has happened a few times more but at least thus far it does seem to be rarer. At first I thought it had something to do with traveling through things: two times I noticed it happening were diving through a door and another was when I landed on something I shouldn't have (a table). After trying both again outside of combat on an ally both times I landed the hits no problem.

As an extension to the above, and no clue if this is new, I can use Jumo (and dragoon dive) to get to places I shouldn't be able to. Such as jumping onto tables or pillars you wouldn't be able to normally get on at all. I was also able to jump across a gap that would normally require me to go up a floor, travel over, then down a floor again to get across. Since this is jumping it does make sense I'd be able to do these things, but I could also see it being unintended.

**Comment by NosVladimir** [comment]
I am also not able to replicate the missing attack reliably.

Jumping is absolutely intended! Have fun exploring the map.

**Comment by Vilacard** [comment]
I think this is a base game bug (I think it existed in Kingmaker) and has nothing to do with Lancer itself, but swapping kinetic blade elements takes a move action. As far as I can tell it should be free since it's technically part of an attack action instead of an actual weapon.

I've given myself Quick Draw from TTT as a workaround so it's not a huge deal.
