### ISSUE TITLE
Suggestion: lancer archetype

### ISSUE THREAD

**Issue by deng-tianhan** [NosVladimir/KineticArchetypes#4]
Not sure how's the progress on the WIP lancer archetype, but here are some ideas:

1. Use charge animation.
2. Alternatively, use teleport animation (similar to blade dash) to get around difficult terrain
3. Make kinetic spear behave like lance (higher damage multiplier) on charge, dive, etc. (Or maybe esoteric blade should get this instead?)
5. Make kinetic spear dual wieldable (does the archetype work with duelist?)

**Comment by NosVladimir** [comment]
The kinetic lancer archetype is about half way done.

I've made some nice visuals for the leap, which is as realistic, smooth and cool as I can get, so definitely stay tuned and look forward to it with high expectations.

Kinetic spear will visually look like a two-handed longspear, using two hands to attack just like a proper longspear. For that reason, you won't be allowed to equip an offhand weapon, otherwise the animation will be weird and will ruin the style. However it's impossible to change the kinetic blade's type from a 'Light, One-handed, Kinetic Blast' weapon to an actual 'Two-handed, Kinetic Blast' weapon without creating a new weapon blueprint for each kinetic blade weapon of different blasts, so the kinetic spear is not gonna benefit from things that work with actual two-handed weapons, like higher bonuses from Power Attack.

Since dragoon dive is too superior in its mechanism (basically jump to anywhere you can see, then full attack with composite blast blade with 0 burn), I'm not going to enhance the offensive abilities of a kinetic lancer beyond what they already have. On multiclassing, 12th level esoteric blade does get the additional crit multiplier since longspears are inherently 20(x3), which brings the kinetic spear to 19-20(x3). Impaling crash is also incredibly strong - any target affected is guaranteed to waste at least a standard action to remove the spike - so no more additional utilities. 

Duel wieldable is not possible for the reasons above, also because both kinetic lancers and kinetic duelists trade supercharge for other stuff so they are not allowed to multi-archetype in the first place.
